name: Bump formulae on schedule or request

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*.ya?ml'
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom list of formulae to livecheck and bump if outdated
        required: false
  schedule:
    # Every 3 hours with an offset of 15 minutes
    - cron: "15 */3 * * *"

env:
  HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1
  FORMULAE: >
    abcmidi
    abseil
    access
    ack
    act
    actionlint
    activemq
    ada-url
    adb-enhanced
    adios2
    afflib
    agda
    age
    age-plugin-yubikey
    agg
    aichat
    alda
    algol68g
    aliddns
    aliyun-cli
    all-repos
    allure
    alluxio
    alp
    alpscore
    alsa-lib
    amber
    ammonite-repl
    amqp-cpp
    amtterm
    ancient
    angle-grinder
    angular-cli
    animdl
    ansible
    ansible-language-server
    ansible-lint
    ant
    ant@1.9
    antidote
    antlr
    antlr4-cpp-runtime
    anycable-go
    aom
    apache-archiva
    apache-drill
    apache-flink
    apache-geode
    apache-opennlp
    apache-spark
    apachetop
    apidoc
    apko
    apktool
    appium
    apr
    apt
    aptos
    arb
    archi-steam-farm
    argo
    argocd
    argocd-autopilot
    argocd-vault-plugin
    argparse
    arkade
    armadillo
    arp-scan
    arrayfire
    artillery
    arturo
    asciidoctorj
    asdf
    ask-cli
    asnmap
    assh
    ast-grep
    astgen
    astro
    asuka
    asymptote
    asyncapi
    atlantis
    atlas
    atuin
    auditbeat
    autorest
    autorestic
    avrdude
    awk
    aws-amplify
    aws-cdk
    aws-elasticbeanstalk
    aws-es-proxy
    aws-nuke
    aws-rotate-key
    aws-sam-cli
    aws-sso-cli
    awscli
    awscli@1
    azcopy
    b2-tools
    b3sum
    babel
    bagit
    baidupcs-go
    balena-cli
    ballerina
    bandwhich
    bareos-client
    bartycrouch
    base16384
    bash_unit
    bash-language-server
    bashunit
    bat
    bat-extras
    batik
    bazarr
    bazel
    bazelisk
    bbtools
    bcftools
    bcoin
    bde
    beagle
    bear
    benthos
    berglas
    bettercap
    bfs
    biber
    bibtexconv
    bigloo
    bilix
    binaryen
    bind
    bindfs
    bindgen
    bingrep
    biome
    bitrise
    bitwarden-cli
    bk
    bkt
    black
    bluepill
    bmake
    bnd
    boolector
    bore-cli
    borgmatic
    bosh-cli
    botan
    bottom
    brev
    brew-php-switcher
    brogue
    brook
    broot
    btrfs-progs
    bubblewrap
    buf
    buildifier
    buildkit
    buildozer
    buildpulse-test-reporter
    buku
    bulk_extractor
    bundletool
    bup
    bupstash
    busted
    butane
    byacc
    byteman
    bzt
    c-ares
    c2rust
    caddy
    cadence
    cadence-workflow
    cadical
    caf
    caire
    calc
    calcurse
    calicoctl
    capnp
    capstone
    cargo-about
    cargo-audit
    cargo-binstall
    cargo-bloat
    cargo-c
    cargo-crev
    cargo-deny
    cargo-depgraph
    cargo-edit
    cargo-generate
    cargo-instruments
    cargo-llvm-lines
    cargo-make
    cargo-nextest
    cargo-outdated
    cargo-release
    cargo-udeps
    cargo-watch
    cargo-zigbuild
    carla
    carrot2
    cask
    cassandra
    cassandra-cpp-driver
    cassandra-reaper
    cassowary
    castxml
    catch2
    cava
    cbindgen
    ccache
    cdebug
    cdk8s
    cdktf
    cdogs-sdl
    cdxgen
    censys
    certbot
    certigo
    cfengine
    cfitsio
    cfn-lint
    cfonts
    cfr-decompiler
    cfssl
    cgl
    cgrep
    chain-bench
    chainloop-cli
    chamber
    charmcraft
    chars
    chart-testing
    chatblade
    cheat
    check-jsonschema
    checkbashisms
    checkdmarc
    checkmake
    checkstyle
    chezmoi
    chkrootkit
    choose-rust
    chromaprint
    chronograf
    chuck
    cilium-cli
    cimg
    circleci
    circumflex
    clair
    clamav
    clarinet
    clazy
    clhep
    cli53
    clickhouse-cpp
    cliclick
    clifm
    clipboard
    clojurescript
    closure-compiler
    cloud-nuke
    cloud-sql-proxy
    cloudflare-quiche
    cloudflare-wrangler2
    cloudflared
    cloudformation-cli
    cloudformation-guard
    cloudprober
    clusterawsadm
    clusterctl
    cmctl
    cmu-pocketsphinx
    cntb
    cobalt
    cocoapods
    cocogitto
    coconut
    code-cli
    code-minimap
    code-server
    codec2
    coder
    codespell
    cog
    cointop
    coinutils
    colima
    commitizen
    commitlint
    composer
    conan
    conan@1
    conda-lock
    conda-zsh-completion
    conduit
    condure
    conftest
    consul-template
    contentful-cli
    convco
    convox
    cookiecutter
    copa
    copier
    copilot
    core-lightning
    coredns
    corepack
    corrosion
    cortex
    cosign
    couchdb
    countdown
    counterfeiter
    coursier
    cp2k
    cpm
    cpp-httplib
    cppcheck
    cpr
    cpu_features
    cpufetch
    cpuid
    crane
    croaring
    croc
    cromwell
    crowdin
    crun
    cryptominisat
    crystal
    css-crush
    csvq
    csvtk
    ctlptl
    cubejs-cli
    cue
    cvs-fast-export
    cweb
    cyclonedx-python
    cycode
    cypher-shell
    cyrus-sasl
    czg
    czkawka
    d2
    daemon
    dafny
    dagger
    darkstat
    dart-sdk
    dartsim
    dasel
    datafusion
    datalad
    datasette
    datree
    dav1d
    dbdeployer
    dbml-cli
    dbus
    dcd
    ddcutil
    ddrescue
    deark
    debianutils
    dehydrated
    delve
    deno
    dependency-check
    deployer
    derby
    detect-secrets
    detekt
    detox
    devcontainer
    devspace
    dex2jar
    dfmt
    dfu-programmer
    dhall
    dhall-bash
    dhall-json
    dhall-lsp-server
    dhall-yaml
    diamond
    diesel
    diffoscope
    difftastic
    digdag
    direvent
    dislocker
    distrobox
    dive
    django-completion
    djhtml
    djl-serving
    dnscontrol
    dnscrypt-proxy
    dnsdist
    dnsmasq
    dnsperf
    dnstwist
    dnsx
    docker
    docker-buildx
    docker-compose
    docker-credential-helper
    docker-credential-helper-ecr
    docker-gen
    docker-machine
    docker-slim
    docker-squash
    dockviz
    doctest
    doctl
    docuum
    doggo
    dolphie
    dolt
    dooit
    dosbox-staging
    dotenv-linter
    double-conversion
    doxygen
    dpkg
    dpp
    dprint
    draco
    drafter
    driftctl
    drill
    drone-cli
    dronedb
    druid
    dscanner
    dsda-doom
    dsq
    dssim
    dstask
    dtm
    dua-cli
    dub
    duck
    duckdb
    duckscript
    dufs
    dumpling
    dunamai
    dune
    dust
    dvc
    dxpy
    dyld-headers
    dynaconf
    dynare
    dysk
    dzr
    earthly
    easeprobe
    easy-rsa
    easyengine
    eccodes
    ecflow-ui
    echidna
    ecl
    editorconfig-checker
    efl
    efm-langserver
    eg-examples
    eget
    ehco
    eigenpy
    ejabberd
    ejdb
    eksctl
    elan-init
    elektra
    elfutils
    elfx86exts
    elixir
    elixir-ls
    elm-format
    elvish
    emacs-dracula
    embree
    embulk
    emqx
    emscripten
    entr
    envconsul
    envd
    envoy
    enzyme
    epr
    erdtree
    erg
    erigon
    erofs-utils
    esbuild
    eslint
    esphome
    esptool
    etcd
    etcd-cpp-apiv3
    ethereum
    eva
    exercism
    exim
    exiv2
    exodriver
    exploitdb
    eza
    f2
    faas-cli
    fabric
    fabric-installer
    fail2ban
    faiss
    fakeroot
    falco
    fantom
    fastfec
    fastlane
    fastnetmon
    fastp
    fastqc
    faust
    fclones
    fd
    fdroidcl
    felinks
    fend
    fennel
    feroxbuster
    ffuf
    fheroes2
    fig2dev
    filebeat
    findent
    findomain
    fisher
    flac
    flank
    flann
    flashrom
    flatbuffers
    fleet-cli
    flint
    flix
    fluent-bit
    fn
    fnm
    folderify
    fontconfig
    fontforge
    fonttools
    fop
    forcecli
    ford
    forgit
    fork-cleaner
    fortio
    fourmolu
    freeipmi
    freerdp
    freeswitch
    freetds
    freetype
    freexl
    frei0r
    frugal
    fselect
    fsql
    fuc
    fuego-firestore
    func-e
    functionalplus
    fuse-overlayfs
    fw
    fwupd
    fx
    faudio
    fblog
    fdroidserver
    feh
    fennel
    feroxbuster
    ffsend
    findomain
    firebase-cli
    firefoxpwa
    flac
    flank
    flarectl
    fleet-cli
    flow-cli
    fluent-bit
    flume
    flyway
    fmt
    fn
    fontforge
    fop
    ford
    fortio
    frugal
    fselect
    func-e
    fuse-overlayfs
    fuseki
    futhark
    gatsby-cli
    gau
    gdu
    geeqie
    geph4
    gerbil-scheme
    gh
    ghz
    ghz-web
    gickup
    gifski
    ginac
    git-annex
    git-cliff
    git-delta
    git-lfs
    git-town
    gitbackup
    gitbucket
    gitea
    gitlab-runner
    gitleaks
    gitql
    glassfish
    gleam
    global
    glooctl
    gmailctl
    gmic
    gmsh
    gnunet
    gnupg-pkcs11-scd
    gnuplot
    go-feature-flag-relay-proxy
    go-md2man
    goffice
    gofumpt
    gojq
    golang-migrate
    golangci-lint
    google-java-format
    goose
    gopass
    gopls
    gor
    goredo
    goreleaser
    goreman
    gosec
    gostatic
    govc
    gowsdl
    gpg-tui
    gpsim
    gradle
    gradle-completion
    gradle-profiler
    grafana
    grafana-agent
    grails
    grin
    gromacs
    groovy
    groovysdk
    gsmartcontrol
    gsoap
    gupnp
    gupnp-tools
    hadoop
    halide
    hapi-fhir-cli
    hasura-cli
    hcloud
    helm
    helmfile
    helmsman
    hexyl
    hidapi
    himalaya
    hive
    hivemind
    hledger
    hoverfly
    hpack
    htmldoc
    htmlq
    htmltest
    htpdate
    httpx
    httpyac
    hyperfine
    iamy
    igv
    imagemagick
    imagemagick@6
    imap-backup
    imapsync
    imgproxy
    influxdb
    influxdb-cli
    influxdb@1
    inxi
    ioctl
    ipinfo-cli
    ipmiutil
    ipopt
    ircd-hybrid
    istioctl
    ittapi
    ivy
    jadx
    jaq
    java-service-wrapper
    jena
    jenkins
    jenkins-job-builder
    jenkins-lts
    jetty
    jfrog-cli
    jhipster
    jmeter
    jnethack
    jql
    jrnl
    jruby
    jsonnet
    jsvc
    juju
    just
    k2tf
    k3d
    k3sup
    k6
    k9s
    kafka
    kahip
    kalker
    kamel
    kapacitor
    kcat
    kcptun
    keptn
    kepubify
    keydb
    ki
    kickstart
    kind
    kitchen-sync
    kn
    knot
    knot-resolver
    ko
    kompose
    kops
    kor
    kotlin
    krew
    ktlint
    kube-linter
    kubeaudit
    kubebuilder
    kubecfg
    kubecm
    kubeconform
    kubergrunt
    kubernetes-cli
    kubeseal
    kubespy
    kubevela
    kubevious
    kubie
    kumactl
    kustomize
    kyma-cli
    kyverno
    lacework-cli
    languagetool
    latex2html
    latexml
    lazydocker
    ld-find-code-refs
    lean-cli
    lefthook
    lego
    leiningen
    lexbor
    lexicon
    lf
    libdap
    libepoxy
    libgetdata
    libgr
    libgsf
    liblinear
    libnfs
    liboqs
    libpano
    libpipeline
    librdkafka
    librespot
    libressl
    libsndfile
    lima
    linkerd
    linode-cli
    liquibase
    llm
    lmod
    localstack
    locust
    log4cxx
    lout
    luau
    luit
    lux
    lychee
    macchina
    mackup
    mage
    mailutils
    manifest-tool
    mapcidr
    marked
    marp-cli
    matterbridge
    maven
    mavsdk
    mawk
    maxwell
    mdbook
    mdcat
    mdzk
    meilisearch
    melody
    memcached
    mesa
    meson
    metabase
    micro
    micronaut
    mill
    mimirtool
    minetest
    minikube
    miniserve
    mmark
    mmctl
    moar
    mockery
    mockserver
    moco
    molecule
    mongocli
    mongodb-atlas-cli
    monika
    monolith
    moto
    mpv
    muffet
    murex
    mutt
    mydumper
    mypy
    naabu
    nagios
    nanoflann
    nativefier
    nats-server
    nats-streaming-server
    naturaldocs
    navi
    ncspot
    needle
    neo4j
    neofetch
    neomutt
    nerdctl
    nest
    netdata
    nethogs
    netlify-cli
    newrelic-cli
    newrelic-infra-agent
    nfpm
    nng
    node_exporter
    node-sass
    notcurses
    nsq
    nuclei
    numcpp
    nushell
    oauth2_proxy
    oauth2c
    ocaml-findlib
    oci-cli
    ocp
    ocrmypdf
    octave
    oh-my-posh
    oha
    okteto
    omniorb
    onednn
    onedrive
    ooniprobe
    opa
    openiothub-server
    openrtsp
    opensearch
    openvdb
    operator-sdk
    optipng
    or-tools
    oras
    orc-tools
    orientdb
    orocos-kdl
    ortp
    osc
    osm
    osv-scanner
    ott
    oxipng
    pacapt
    passenger
    patchelf
    payara
    pdftk-java
    pdm
    pdnsrec
    pgbadger
    pgbouncer
    pgloader
    pgweb
    phoronix-test-suite
    php-code-sniffer
    php-cs-fixer
    phpmd
    phpmyadmin
    phpstan
    pianod
    picard-tools
    pig
    pillow
    plantuml
    plow
    pmd
    pngquant
    pnpm
    pocketbase
    podman
    postgis
    powerman
    pre-commit
    prestd
    prestodb
    principalmapper
    procs
    protoc-gen-go-grpc
    psalm
    pstoedit
    pueue
    pushpin
    pwntools
    py-spy
    pyflow
    pyoxidizer
    qd
    qjackctl
    qpid-proton
    questdb
    quick-lint-js
    quicktype
    radamsa
    rancher-cli
    rav1e
    rbspy
    rbw
    rclone
    rcs
    rebar3
    recode
    regina-rexx
    regula
    reminiscence
    reposurgeon
    revive
    rhit
    riemann
    rke
    rollup
    rosa-cli
    rover
    rpg-cli
    rqlite
    rubberband
    rustup-init
    s-search
    s2n
    saml2aws
    sbt
    scala
    scorecard
    scotch
    scrcpy
    scummvm
    scummvm-tools
    scw
    sdl2
    seaweedfs
    selene
    selenium-server
    seqkit
    ser2net
    serverless
    shadowenv
    sheldon
    shellharden
    shellz
    shfmt
    signal-cli
    silicon
    singularity
    sjk
    skaffold
    skopeo
    skylighting
    slackcat
    sleuthkit
    slides
    smimesign
    sn0int
    sniffer
    sniffglue
    snyk-cli
    solana
    sollya
    solr
    sonarqube
    sonobuoy
    sponge
    spotbugs
    spotify-tui
    sqlancer
    sqlc
    sqlmap
    sqlx-cli
    sshs
    sslyze
    stanford-corenlp
    starship
    staticcheck
    statix
    stdman
    stellar-core
    step
    storm
    streamlink
    stress-ng
    structurizr-cli
    stunnel
    stylish-haskell
    subfinder
    subversion
    suite-sparse
    sundials
    suricata
    svgbob
    svgo
    svtplay-dl
    swagger-codegen
    swagger-codegen@2
    swagger2markup-cli
    syncthing
    sysdig
    talisman
    tanka
    tcsh
    tctl
    tealdeer
    tectonic
    tektoncd-cli
    teku
    teleport
    tendermint
    tengo
    termshark
    terracognita
    terraform-inventory
    terraform-ls
    terraform-provider-libvirt
    terraform-rover
    terraformer
    terragrunt
    terrascan
    testkube
    tfsec
    thanos
    thrift
    tika
    tile38
    timg
    tm
    toast
    tomcat
    tomcat-native
    tomcat@8
    tomcat@9
    tomee-plus
    tomee-webprofile
    topgrade
    traefik
    trafficserver
    tree-sitter
    triangle
    trivy
    trojan-go
    trufflehog
    typedb
    typos-cli
    tz
    uni
    universal-ctags
    v2ray
    vala
    valabind
    vale
    vapoursynth
    vault-cli
    veclibfort
    velero
    verapdf
    vercel-cli
    vgrep
    virgil
    virustotal-cli
    vite
    vitess
    vivid
    vnstat
    volta
    vpn-slice
    vsearch
    vsh
    vue-cli
    wabt
    wakatime-cli
    wallpaper
    wapm
    wartremover
    wasm-pack
    wasmer
    wasmtime
    watchexec
    webdis
    webp
    webpack
    websocat
    webtorrent-cli
    wgcf
    whistle
    whois
    wildfly-as
    wireguard-go
    wiremock-standalone
    wolfssl
    woodpecker-cli
    wxwidgets
    xcbeautify
    xclogparser
    xdpyinfo
    xeol
    xerces-c
    xgboost
    xh
    xplr
    xray
    yaegi
    ykman
    yosys
    youtubedr
    yq
    z3
    zabbix
    zbctl
    zellij
    zenith
    znapzend
    zola
    zookeeper
    zoxide
    zsh-vi-mode
    zstd
    zydis

permissions:
  contents: read

jobs:
  autobump:
    if: github.repository == 'Homebrew/homebrew-core'
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          cask: false
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'BrewTestBot' }}

      - name: Bump formulae
        uses: Homebrew/actions/bump-packages@master
        continue-on-error: true
        with:
          token: ${{ secrets.HOMEBREW_CORE_REPO_WORKFLOW_TOKEN }}
          formulae: ${{ github.event.inputs.formulae || env.FORMULAE }}
